ibexa/graphql

src/bundle/DependencyInjection/Configuration.php, src/bundle/DependencyInjection/IbexaGraphQLExtension.php, src/bundle/IbexaGraphQLBundle.php
Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1589](https://issues.ibexa.co/browse/IBX-1589)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | no, not used
Fixed registering Ibexa GraphQL extension with custom alias `ibexa_graphql` (by default Symfony generated `ibexa_graph_ql`).
Since extension does not provide any configuration, this change is only a formality not affecting the Product in any way.
- ~Provided automated test coverage.~ // full stack Behat coverage
=> IBX-1589: Fixed & renamed Extension ezplatform_graphql to ibexa_graphql

spec/Schema/Builder/SchemaBuilderSpec.php, spec/Schema/Domain/Content/ContentDomainIteratorSpec.php, src/bundle/Resources/config/services/schema.yaml, src/lib/Schema/Builder/SchemaBuilder.php, src/lib/Schema/Domain/Content/ContentDomainIterator.php, src/lib/Schema/Domain/ImageVariationDomain.php
Parent PR: https://github.com/ezsystems/ezplatform-graphql/pull/116
=> Merge IBX-1565: Refactor schema's types' names validation

src/bundle/Resources/config/services/schema.yaml
> JIRA: -
Follow up for https://github.com/ibexa/graphql/pull/14. 
```
!!  In AbstractRecursivePass.php line 186:
!!                                                                                 
!!    Invalid service "Ibexa\GraphQL\Schema\Domain\ImageVariationDomain": method   
!!    "setLogger()" does not exist.    
```
=> IBX-1565: Fixed invalid Ibexa\GraphQL\Schema\Domain\ImageVariationDomain service

doc/domain_schema.md, src/bundle/DependencyInjection/Compiler/FieldInputHandlersPass.php, src/bundle/DependencyInjection/Compiler/RichTextInputConvertersPass.php, src/bundle/DependencyInjection/Compiler/SchemaDomainIteratorsPass.php, src/bundle/DependencyInjection/Compiler/SchemaWorkersPass.php, src/bundle/Resources/config/services/mutations.yaml, src/bundle/Resources/config/services/schema.yaml
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1694](https://issues.ibexa.co/browse/IBX-1694)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#12
In this Pull Request we rename Ibexa's dependency injection container service tags according to the map provided by ibexa/compatibility-layer#12 as a part of the rebranding process. Backward compatibility for old service tags is provided by ibexa/compatibility-layer#12.
=> IBX-1694: Rebranded dependency injection container service tags

doc/howto/custom_field_type.md, src/bundle/DependencyInjection/IbexaGraphQLExtension.php, src/bundle/Resources/config/default_settings.yaml, src/bundle/Resources/config/services/schema.yaml, src/bundle/Resources/config/services/services.yaml, src/lib/Resolver/SiteaccessGuesser/SiteaccessGuesser.php
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1696](https://issues.ibexa.co/browse/IBX-1696)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#31
Rebranded service container parameter names and Ibexa Config Resolver namespaces to follow unified pattern
=> IBX-1696: Rebranded Container parameters and Config Resolver namespaces

composer.json, doc/custom_app_schema.md, doc/howto/upload_binary_files.md, src/bundle/Resources/config/graphql/Content.types.yaml, src/bundle/Resources/config/graphql/ContentType.types.yaml, src/bundle/Resources/config/graphql/FieldDefinition.types.yaml, src/bundle/Resources/config/graphql/Location.types.yaml, src/bundle/Resources/config/graphql/ObjectState.types.yaml, src/bundle/Resources/config/graphql/ObjectStateGroup.types.yaml, src/bundle/Resources/config/graphql/Platform.types.yaml, src/bundle/Resources/config/graphql/Repository.types.yaml, src/bundle/Resources/config/graphql/Section.types.yaml, src/bundle/Resources/config/graphql/User.types.yaml, src/lib/Mutation/InputHandler/FieldType/RichText/HtmlRichTextConverter.php, src/lib/Mutation/InputHandler/FieldType/RichText/MarkdownRichTextConverter.php, src/lib/Schema/Domain/Content/Mapper/FieldDefinition/ConfigurableFieldDefinitionMapper.php
=> IBX-1853: Used rebranded Ibexa name in codebase

composer.json, spec/Schema/Domain/Content/NameHelperSpec.php, spec/Schema/Domain/Content/Worker/ContentType/AddItemOfTypeConnectionToGroupSpec.php, src/bundle/Resources/config/graphql/DomainContent.types.yaml, src/bundle/Resources/config/graphql/Item.types.yaml, src/lib/Schema/Builder/Input/Type.php, src/lib/Schema/Builder/SchemaBuilder.php, src/lib/Schema/Domain/Content/Worker/ContentType/DefineItemConnection.php
JIRA https://issues.ibexa.co/browse/IBX-1993.
This PR aims to bump `overblog/graphql` dependency which offers full support for PHP8. Changes were required to adjust definitions that were lacking `nodeType` configuration key.
=> IBX-1993: Upgrade overblog/graphql-bundle to v0.14

composer.json, src/lib/Relay/DomainConnectionBuilder.php, src/lib/Relay/PageAwareConnection.php, src/lib/Relay/SearchResolver.php
JIRA: https://issues.ibexa.co/browse/IBX-2424
Due to upgrading `overblog/graphql` to 0.14 there are some leftovers related to:
- `ConnectionBuilder` namespace change, ref: https://github.com/overblog/GraphQLBundle/blob/master/UPGRADE.md#remove-connectionbuilder-deprecated-class
- changes to Relay Paginator and setting its properties, ref: https://github.com/overblog/GraphQLBundle/blob/master/UPGRADE.md#relay-paginator-connections--edges
=> IBX-2424: Fixed deprecation leftovers after upgrading `overblog/graphql` to v0.14

src/bundle/Command/GeneratePlatformSchemaCommand.php
JIRA: https://issues.ibexa.co/browse/IBX-2467
>Currently, `ibexa:graphql:generate-schema` command does not set admin permissions by default. This leads to empty results e.g. when utilizing `ProductTypeService::findProductTypes` due to `View` permissions check, ref: https://github.com/ibexa/product-catalog/blob/main/src/lib/Local/Repository/ProductTypeService.php#L305.
=> IBX-2467: Added `admin` repository permissions

spec/Schema/Domain/Content/NameHelperSpec.php, src/bundle/Resources/config/services/schema.yaml, src/bundle/Resources/config/services/services.yaml, src/lib/Schema/Domain/BaseNameHelper.php, src/lib/Schema/Domain/Content/NameHelper.php, src/lib/Schema/Domain/Content/Pluralizer.php, src/lib/Schema/Domain/Pluralizer.php
JIRA: https://issues.ibexa.co/browse/IBX-2355
In order to reuse methods `pluralize` and `toCamelCase` within https://github.com/ibexa/product-catalog/pull/456 we need to change their scope to be able to decorate the original implementation and avoid redundancy.
=> IBX-2355: Made inheritance of the naming methods possible

spec/Schema/Domain/Content/Worker/ContentTypeGroup/AddDomainGroupToDomainSpec.php, spec/Schema/Domain/Content/Worker/ContentTypeGroup/DefineDomainGroupSpec.php, spec/Schema/Domain/Content/Worker/ContentTypeGroup/DefineDomainGroupTypesSpec.php, src/lib/Relay/NodeResolver.php, src/lib/Schema/Domain/Content/NameHelper.php, src/lib/Schema/Domain/Content/Worker/ContentTypeGroup/AddDomainGroupToDomain.php, src/lib/Schema/Domain/Content/Worker/ContentTypeGroup/DefineDomainGroup.php, src/lib/Schema/Domain/Content/Worker/ContentTypeGroup/DefineDomainGroupTypes.php
> JIRA: -
Fixed deprecated \Ibexa\GraphQL\Schema\Domain\Content\NameHelper::domain* method usages
=> Fixed deprecated NameHelper::domain* method usages

src/bundle/DependencyInjection/GraphQL/YamlSchemaProvider.php, src/bundle/DependencyInjection/IbexaGraphQLExtension.php
JIRA ticket: https://issues.ibexa.co/browse/IBX-2899
**Followup PR for Platform.sh**: https://github.com/ibexa/post-install/pull/43
JIRA excerpt:
>There is a leftover in form of the not yet rebranded `config/graphql/types/ezplatform` folder where the schema is stored. It should be just changed to `config/graphql/types/ibexa`.
This change should be also reflected in the documentation, ref: https://doc.ibexa.co/en/latest/api/graphql/#setup.
=> IBX-2899: Rebranded schema storage directory to `/config/graphql/types/ibexa`

src/bundle/DependencyInjection/GraphQL/YamlSchemaProvider.php, src/bundle/Resources/config/graphql/PlatformMutation.types.yaml, src/lib/Schema/Domain/Content/Worker/ContentType/DefineItemMutation.php
Question | Answer
-- | --
JIRA issue | https://issues.ibexa.co/browse/IBX-869
Type | bugfix
Target Ibexa DXP version | v4.2.x
BC breaks | maybe (custom mutations may have to be updated in the same way)
The schema mutation type is set by detecting what files were generated. When https://github.com/ezsystems/ezplatform-graphql/pull/90 was merged, `DomainContentMutation.types.yaml` was renamed to `ItemMutation.types.yaml`, but the `YamlSchemaProvider` that searches for the files was not updated.
In addition, in v0.14 of overblog/graphql-bundle, the `mutation` function, used to resolve mutations, has been changed. The arguments are not provided as an array anymore, but as regular function arguments. This is the reason for the [error @mnocon …
=> IBX-869: Fixed loading of mutations schema

composer.json
> JIRA: -
webonyx/graphql-php introduces several BC breaks: https://github.com/webonyx/graphql-php/releases/tag/v15.0.0 however dependency declaration in https://github.com/overblog/GraphQLBundle/blob/0.14/composer.json#L46 is open
Ref. https://github.com/ibexa/product-catalog/actions/runs/3866379035/jobs/6590463810#step:8:72
=> Added conflict with webonyx/graphql-php >= 15.0.0

src/bundle/Resources/config/graphql/Item.types.yaml, src/lib/Resolver/DomainContentMutationResolver.php
**JIRA:** [IBX-4415](https://issues.ibexa.co/browse/IBX-4415)
=> IBX-4415: Fixed `createDomainContent` mutation

src/lib/Mapper/ContentImageAssetMapperStrategy.php, src/lib/Value/ContentFieldValue.php
From phpDocumentor v3.3.1:
* `Unable to parse file "vendor/ibexa/graphql/src/lib/Mapper/ContentImageAssetMapperStrategy.php", an error was detected: A type is missing after a type separator`
* `Unable to parse file "vendor/ibexa/graphql/src/lib/Value/ContentFieldValue.php", an error was detected: The tag "@" does not seem to be wellformed, please check it for errors`
=> IBX-4929: Fix phpDoc

composer.json, src/bundle/Resources/config/graphql/ContentType.types.yaml, src/bundle/Resources/config/graphql/DomainContent.types.yaml, src/bundle/Resources/config/graphql/Item.types.yaml, src/bundle/Resources/config/graphql/User.types.yaml, src/bundle/Resources/config/services/resolvers.yaml, src/lib/Resolver/ThumbnailResolver.php
https://issues.ibexa.co/browse/IBX-6602
There is no need for it, as thumbnails can be obtained directly from Content::getThumbnail or User::getThumbnail.
Done this way, instead of doing user.getContent(), as accessing `content` from user object is deprecated.
As it had `type: "UserItem"` but it was resolved to `value` it was not UserItem, but actual User object.
As it is possible now, to obtain thumbnails by accessing content on user object like this:
```graphql
{
content {
folder(contentId: 81) {
_contentInfo {
owner {
id
content {
_thumbnail {
uri
}
}
}
}
}
}
}
```
accessing content on user is deprecated (since 6,10 ;) ), so new property was added to match php API
```graphql
{
content {
folder (contentId: 81) {
id,
_contentInfo {
owner{
thumbnail {
uri,
},
}
}
}
}
}
```
`resolve: …
=> IBX-6602: Used Content::getThumbnail directly for obtaining thumbnails

src/bundle/Resources/config/graphql/Content.types.yaml, src/bundle/Resources/config/graphql/ContentType.types.yaml, src/bundle/Resources/config/graphql/DomainContent.types.yaml, src/bundle/Resources/config/graphql/Item.types.yaml, src/lib/Resolver/DomainContentMutationResolver.php, src/lib/Schema/Domain/Content/ContentDomainIterator.php, src/lib/Value/ContentFieldValue.php
| Question                                  | Answer |
| ---------------------------------------- | ------------------ |
| **JIRA issue**                          | [IBX-7409](https://issues.ibexa.co/browse/IBX-7409) |
| **Type**                                   | bug |
| **Target Ibexa version** | `v4.6`|
| **BC breaks**                          | no |
Changed Content Type label to Content type
=> IBX-7409: Changed Content Type label to content type

src/lib/Schema/Domain/Content/Mapper/FieldDefinition/ResolverVariables.php
https://issues.ibexa.co/browse/IBX-7979
Performing simple `str_replace` on fieldtypes' identifiers like `my_custom_field` instead of
```
'@=resolver("MatrixFieldValue", [value, "my_custom_field"])'
```
produced something like:
```
@=resolver("MatrixFieldValue", [value, "my_custom_resolver("ItemFieldValue", [value, "' . $fieldDefinition->identifier . '", args])"])
```
which is obviously an invalid schema entry.
Decided to just narrow down the actual replacing to values **not being inside double quotes**. The reason for that is that we have several scenarios to be handled like `[field]`, `@=field`, `"@=resolver("Page", [field, context])"` etc. where current `str_replace` needs to be invoked.
=> IBX-7979: Fixed "field" occurrences being wrongly replaced

src/lib/Schema/Domain/Content/Mapper/FieldDefinition/ResolverVariables.php
JIRA: https://issues.ibexa.co/browse/IBX-7979
Followup for https://github.com/ibexa/graphql/pull/59 where `return` was performed too early. I added also some more strict regular expression targeting only actual usage of `field` keyword within fields' identifiers with case-insensitivity taken into account.
=> IBX-7979: Fixed "field" keyword occurrences in fields' identifiers being wrongly replaced

composer.json
=> Fixed missing `ibexa/notifications` dev dependency

src/bundle/Command/GeneratePlatformSchemaCommand.php
=> IBX-8224: Dropped BackwardCompatibleCommand

src/bundle/Command/GeneratePlatformSchemaCommand.php, src/bundle/DependencyInjection/Configuration.php, src/bundle/IbexaGraphQLBundle.php, src/lib/Value/ContentFieldValue.php, src/lib/Value/Field.php
| :ticket: Issue | IBX-8138 |
Applied rules from Symfony 5 Rector set lists.
No QA needed. Regression tests should be enough.
This is code refactoring without behavior change. No documentation changes needed.
=> IBX-8138: [Rector] Applied rules from Symfony 5 Rector set lists

phpstan-baseline.neon, src/bundle/Resources/config/services/resolvers.yaml, src/lib/Resolver/ContentResolver.php
=> IBX-8534: Dropped ContentService::loadRelations usage

src/bundle/Resources/config/default_settings.yaml, src/bundle/Resources/config/graphql/Field.types.yaml, src/bundle/Resources/config/services/schema.yaml, src/lib/Schema/Domain/Content/Mapper/FieldDefinition/UrlFieldDefinitionMapper.php
| :ticket: Issue | IBX-7603 |
If the `ibexa.graphql.schema.should.extend.ezurl` parameter is `false` (default), the graphQL query will look like before, i.e.:
```
{
content {
urlCT(contentId:68) {
urlField
}
}
}
```
but if we set this parameter to `true`, the graphQL query will look like this:
```
{
content {
urlCT(contentId:68) {
urlField {
link,
text
}
}
}
}
```
This is port to 4.6 from https://github.com/ezsystems/ezplatform-graphql/pull/137
=> IBX-7603: Added missing subfield for ezurl

src/lib/Resolver/DomainContentMutationResolver.php
| :ticket: Issue | IBX-9040 |
This is a fix for a small oversight in https://github.com/ibexa/graphql/pull/46
When requesting data back after performing an update mutation, certain fields would throw 500 because we are returning Content instead of Item. This behavior has been fixed here.
=> IBX-9040: Fixed return in `updateDomainContent` method to Item

.github/workflows/ci.yaml, composer.json, rector.php, src/bundle/Command/GeneratePlatformSchemaCommand.php
| :ticket: Issue | IBX-9584 |
Enabled and executed automatic refactoring rules defined for Symfony 6.x.
* [CLI] Replaced deprecated Command::{$defaultName, $defaultDescription} with the AsCommand attribute
* [CLI] Dropped ezplatform:graphql:generate-schema alias
Additionally added rector job to CI setup to prevent merging up code which is not compatible with Symfony 6+. 
Sanities.
N/A
=> IBX-9584: Resolved Symfony 6.x deprecations

composer.json, src/lib/Exception/NoValidLocationsException.php
> [!CAUTION]
> # Merge together with other IBX-8471 Pull Requests
> - [x] Make sure TMP commit(s) are dropped before merging
| :ticket: Issue | IBX-8471 |
Upgrading Symfony dependencies to version 7 along with necessary 3rd party packages and codebase changes.
Key changes:
Sanity tests and/or regression builds.
=> IBX-8471: Upgraded codebase to Symfony 7

rector.php, src/bundle/DependencyInjection/IbexaGraphQLExtension.php
| :ticket: Issue | IBX-9968  |
Enabled Rector Symfony 7.0, 7.1 and 7.2 sets. Resolved the following deprecations:
```
[symfony/http-kernel] Replaced usage of internal Symfony\Component\HttpKernel\DependencyInjection\Extension class
```
Sanities.
=> IBX-9968: Resolved Symfony 7.x deprecations

doc/howto/custom_field_type.md, spec/Schema/Domain/Content/Mapper/FieldDefinition/RelationFieldDefinitionMapperSpec.php, spec/Schema/Domain/Content/Mapper/FieldDefinition/SelectionFieldDefinitionMapperSpec.php, spec/Schema/Domain/Content/Worker/FieldDefinition/AddFieldDefinitionToItemTypeSpec.php, src/bundle/Resources/config/default_settings.yaml, src/bundle/Resources/config/graphql/FieldDefinition.types.yaml, src/bundle/Resources/config/services/mutations.yaml, src/bundle/Resources/config/services/resolvers.yaml, src/lib/Mutation/InputHandler/FieldType/Date.php, src/lib/Mutation/InputHandler/FieldType/RichText.php, src/lib/Mutation/UploadFiles.php, src/lib/Schema/Domain/Content/Mapper/FieldDefinition/RelationFieldDefinitionMapper.php, src/lib/Schema/Domain/Content/Mapper/FieldDefinition/SelectionFieldDefinitionMapper.php
| :ticket: Issue | IBX-9947 |
https://github.com/ibexa/core/pull/543
=> IBX-9947: Rebranded field type identifiers
